CREATE TABLE "buses" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "buses_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"origin" text NOT NULL,
	"destination" text NOT NULL,
	"category" text NOT NULL,
	"departure_time" timestamp with time zone NOT NULL,
	"status" text DEFAULT 'On Time' NOT NULL,
	"is_paid" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"modified_at" timestamp with time zone DEFAULT now() NOT NULL
);
