CREATE TABLE "opted_in_emails" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "opted_in_emails_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"email" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "opted_in_emails_email_unique" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "buses" ADD COLUMN "special_origin" text;